# Generated by Django 4.2.1 on 2023-06-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_izlenen'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='katagori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.katagori'),
        ),
    ]
